### ISSUE TITLE
ERROR:You must provide a recipient (including a resource)

### ISSUE THREAD

**Issue by sunshineatnoon** [nplexity/xmpp-file-transfer-demo#12]
Your code is a great guide for learning xmpp-file-transfer, thanks for it.
However I got this error when try to send a piece to another client:
FileTransferDemo[3957:607] You messed something up: Error Domain=XMPPOutgoingFileTransferErrorDomain Code=-1 "You must provide a recipient (including a resource)." UserInfo=0x7fccfa63cf00 {NSLocalizedDescription=You must provide a recipient (including a resource).}
I double check that both clients are online when tranffering file. Also there is a piece of audio file in the directory.
How to solve this error?

**Comment by sunshineatnoon** [comment]
It seems my recipient don't have a rescource, I 'm new to xmpp, what does a resource mean?

**Comment by jonstaff** [comment]
The resource is the device or client through which a user is currently connected.  For example, if my username is `jon@nplexity.com`, then I would be logged in on my phone as `jon@nplexity.com/phone` or on my desktop as `jon@nplexity.com/desktop`.  *phone* and *desktop* are merely examples and it's not required that they be this.

The format is then as follows:

```
<user>@<domain>/<resource>
```

Without a resource, the sender doesn't know where to send the file.

**Comment by sunshineatnoon** [comment]
that's a very clear explanation, thanks!
I checked on my openfire page, I found one of my client's resource is f3042644, this seems to be some random code, how can I set or get this resource?

**Comment by jonstaff** [comment]
The resource is often a randomly generated string.  Are you asking how you can modify it with XMPPFramework?

**Comment by sunshineatnoon** [comment]
Now I am using XMPPJID *recipientJID = [XMPPJID jidWithString:[self.ajid full] resource:@"2b6c9fd9"]; to set resource manually to avoid the error above, if it's random, how can I get it in my program.

**Comment by jonstaff** [comment]
When you call `[self.ajid full]`, it's already returning the entire JID in the form described above.

You can just call `[self.ajid resource]` or `self.ajid.resource` to return the resource as an NSString.

**Comment by jonstaff** [comment]
If you want to edit the resource, use the [method found here](https://github.com/robbiehanson/XMPPFramework/blob/master/Core/XMPPJID.h#L64):

```objc
- (XMPPJID *)jidWithNewResource:(NSString *)resource;
```

**Comment by sunshineatnoon** [comment]
I tried this: XMPPJID *recipientJID = [XMPPJID jidWithString:recipient resource:[[XMPPJID jidWithString:recipient] resource]]; but it doesn't work. I still have to manually set the resource.

Also, I found another problem:
NSLocalizedDescription=Unable to send SI offer; the recipient doesn't have the required features.

**Comment by Arbaz7786** [comment]
I have same issue XMPPOutgoingFileTransferErrorDomain Code=503 I have tried to send a file using this

```
[_fileTransfer sendData:data
                         named:filename
                   toRecipient:[XMPPJID jidWithString:recipient resource:[NSString stringWithFormat:@"%@",[XMPPJID jidWithString:recipient].resource]]
                   description:@"Baal's Soulstone, obviously."
                         error:&err]
```

But not able to send the file please help me.
I have print the `[XMPPJID jidWithString:recipient].resource]` as you mentioned above but it gives null value.
and I am receiving this error

```
Outgoing file transfer failed with error: Error Domain=XMPPOutgoingFileTransferErrorDomain Code=503 "<service-unavailable xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/>" UserInfo=0x7ffb83e983b0 {NSLocalizedDescription=<service-unavailable xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/>}
```

**Comment by jonstaff** [comment]
If your `resource` is nil, the file transfer won't know where to send the outgoing file. You need to declare your JID using a resource.

As mentioned above, view the [method here](https://github.com/robbiehanson/XMPPFramework/blob/master/Core/XMPPJID.h#L64) for doing so.

Additionally, I recommend taking a look at the [XMPP JID XEP here](http://xmpp.org/extensions/xep-0029.html) to become more acquainted with how they work.
