### ISSUE TITLE
Are the file transfer messages history stored in the coredata?

### ISSUE THREAD

**Issue by xhsoldier** [nplexity/xmpp-file-transfer-demo#21]
The messages that are sent/received are stored in the coredata. I can get the history message and display on the view. 
1. Where can I get the file transfer history, are they also stored in the coredata?
2. User can get offline text message when he is online again. How about the file transfer? Will the user get offline file transfer message when he is online again.

**Comment by judges** [comment]
+1

**Comment by xhsoldier** [comment]
OK, at last, I build up a http server for uploading files, and send the url to the client. So the message history would be in the core data. So,
1. even the remote user is offline, when he is online again. he will receive a url message, then dowanload the file.
2. the file transfer history is automatically stored in the message core data.

**Comment by xhsoldier** [comment]
OK, at last, I build up a http server for uploading files, and send the url to the client. So the message history would be in the core data. So,
1. even the remote user is offline, when he is online again. he will receive a url message, then dowanload the file.
2. the file transfer history is automatically stored in the message core data.
