### ISSUE TITLE
Storing and sending file while receiver is offline

### ISSUE THREAD

**Issue by souvickcse** [nplexity/xmpp-file-transfer-demo#7]
Hi jonstaff,
I am using your code, it is working fine when the receiver id is online, but i am getting "service unavailable" when receiver id is offline. Is there any thing we can do about this? Is it possible to add the storing of offline media (like offline chat is stored and send to receiver when the receive comes online) with the current code? Any suggestion ? Any solution ?

**Comment by AbeiOS** [comment]
My god~~555 How did QQ and WeChat  transfer file offline！if i use server to handle this ，it’s pretty low。because my origin Company implement it use server to handle this。

**Comment by AbeiOS** [comment]
au~ it’s two years old。。。
